
[build]
  command = "npm run build"
  publish = "dist" # or "build" depending on your React build output folder

[build.environment]
  NODE_VERSION = "18" # Match your local Node version

[[redirects]]
  from = "/api/*"
  to = "https://host-turf-managment-system-project.onrender.com/:splat"
  status = 200
  force = true

[[headers]]
  # Apply these headers to all paths
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Environment variables (set these in Netlify UI too)
[context.production.environment]
  REACT_APP_API_BASE_URL = "https://host-turf-managment-system-project.onrender.com"
  REACT_APP_ENVIRONMENT = "production"